# Generated by Django 5.2.1 on 2025-05-18 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='named_url',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='is_named_url',
            field=models.BooleanField(default=False, help_text='Отметьте, если в поле URL указано имя маршрута (named url)'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='url',
            field=models.CharField(help_text='Можно указать либо url-имя, либо абсолютный путь', max_length=255),
        ),
    ]
